import { app,BrowserWindow,dialog,ipcMain,Menu,nativeImage,safeStorage,shell,Tray } from 'electron';
import fs from 'node:fs/promises';import fsSync from 'node:fs';import path from 'node:path';import os from 'node:os';import crypto from 'node:crypto';
import { SystemChromeAdapter } from '../core/browser/systemChromeAdapter.js';import { EmbeddedChromiumAdapter } from '../core/browser/embeddedChromiumAdapter.js';import type { BrowserAdapter } from '../core/browser/adapter.js';
import { DouyinCreatorCollector } from '../core/collector/douyin.js';import { loginXmt,register,upload } from '../core/uploader/client.js';import { intervalMs,nextDailyDelay } from '../core/scheduler/scheduler.js';import type { AgentConfig,BrowserMode,SyncResult } from '../core/types.js';import type { DesktopState,SetupInput } from './types.js';
import { CreatorDatabase } from '../core/database/creatorDatabase.js';
app.setName('XMT Creator Agent');
const executableDirectory=path.dirname(app.getPath('exe'));const resourceDirectory=process.resourcesPath;const portableFlagCandidates=[path.join(executableDirectory,'portable.flag'),path.join(resourceDirectory,'portable.flag'),path.join(path.dirname(resourceDirectory),'portable.flag')];const portableMode=portableFlagCandidates.some(candidate=>fsSync.existsSync(candidate));const portableDataRoot=path.join(executableDirectory,'data');if(portableMode){fsSync.mkdirSync(portableDataRoot,{recursive:true});app.setPath('userData',portableDataRoot);}console.log(`[XMT Agent]\nMode: ${portableMode?'Portable':'Standard'}\nData: ${portableMode?portableDataRoot:app.getPath('userData')}`);
let mainWindow:BrowserWindow|null=null;let tray:Tray|null=null;let syncing=false;let timer:NodeJS.Timeout|null=null;let lastSyncAt:string|undefined;let lastError:string|undefined;let chromeConnected=false;let douyinLoggedIn=false;let activeLoginAdapter:BrowserAdapter|null=null;const systemAdapters=new Map<string,SystemChromeAdapter>();let embeddedAdapter:EmbeddedChromiumAdapter|null=null;
const paths=()=>{const root=portableMode?portableDataRoot:app.getPath('userData');return{root,config:path.join(root,'config.json'),token:path.join(root,'agent-token.bin'),profile:path.join(root,'browser'),database:path.join(root,'creator.db'),logs:path.join(root,'logs'),log:path.join(root,'logs','sync.log'),networkLog:path.join(root,'logs','network.json')}};
async function log(message:string){const p=paths();await fs.mkdir(p.logs,{recursive:true});const safe=message.replace(/cookie|password|authorization|token/gi,'[redacted]');await fs.appendFile(p.log,`[${new Date().toISOString()}] ${safe}\n`,'utf8');}
async function readConfig(){try{const config=JSON.parse(await fs.readFile(paths().config,'utf8')) as AgentConfig;if(!config.browserConfig)config.browserConfig={mode:'system_chrome',cdpEndpoint:'http://127.0.0.1:9222'};return config;}catch{return null;}}
async function writeConfig(config:AgentConfig){await fs.mkdir(paths().root,{recursive:true});await fs.writeFile(paths().config,JSON.stringify(config,null,2),'utf8');}
function browserAdapter(config:AgentConfig):BrowserAdapter{if(config.browserConfig.mode==='embedded_chromium'){embeddedAdapter??=new EmbeddedChromiumAdapter(paths().profile);return embeddedAdapter;}const endpoint=config.browserConfig.cdpEndpoint||'http://127.0.0.1:9222';const cacheKey=`${endpoint}|${config.browserConfig.chromePath||'auto'}`;let adapter=systemAdapters.get(cacheKey);if(!adapter){adapter=new SystemChromeAdapter(paths().profile,endpoint,config.browserConfig.chromePath);systemAdapters.set(cacheKey,adapter);}return adapter;}
function protectToken(token:string){if(!safeStorage.isEncryptionAvailable())throw new Error('Windows DPAPI 当前不可用，无法安全保存 Agent 凭据');return safeStorage.encryptString(token);}
async function saveToken(token:string){await fs.writeFile(paths().token,protectToken(token),{mode:0o600});}
async function readToken(){try{return safeStorage.decryptString(await fs.readFile(paths().token));}catch{throw new Error('Agent 凭据不存在或无法由当前 Windows 用户解密，请重新连接');}}
function fingerprint(){return crypto.createHash('sha256').update([os.hostname(),os.platform(),os.arch(),process.env.COMPUTERNAME||'',process.env.USERDOMAIN||''].join('|')).digest('hex');}
async function recentLogs(){try{return(await fs.readFile(paths().log,'utf8')).split(/\r?\n/).filter(Boolean).slice(-100).reverse();}catch{return[];}}
async function state():Promise<DesktopState>{const config=await readConfig();return{connected:Boolean(config&&fsSync.existsSync(paths().token)),configured:Boolean(config),syncing,lastSyncAt,lastError,config:config||undefined,logs:await recentLogs(),autoLaunch:portableMode?false:app.getLoginItemSettings().openAtLogin,portableMode,chromeConnected,douyinLoggedIn};}
async function emit(){const value=await state();mainWindow?.webContents.send('agent:state',value);return value;}
async function performSync():Promise<SyncResult>{if(syncing)throw new Error('同步正在进行中');const config=await readConfig();if(!config)throw new Error('请先连接 XMT 并绑定账号');syncing=true;lastError=undefined;await emit();try{await log(`开始采集创作者中心，浏览器模式 ${config.browserConfig.mode}`);const snapshot=await new DouyinCreatorCollector(browserAdapter(config),paths().networkLog).collect();const database=new CreatorDatabase(paths().database);try{database.save(snapshot);}finally{database.close();}const result=await upload(config,await readToken(),snapshot);lastSyncAt=new Date().toISOString();await log(`同步成功，快照 ${result.snapshot_id||'-'}，作品 ${snapshot.works.length}`);return{collectedAt:lastSyncAt,snapshot,upload:result};}catch(error){lastError=error instanceof Error?error.message:String(error);await log(`同步失败：${lastError}`);throw error;}finally{syncing=false;await emit();}}
async function schedule(){if(timer)clearTimeout(timer);timer=null;const config=await readConfig();if(!config?.syncConfig.enabled||config.syncConfig.interval==='manual')return;const delay=config.syncConfig.interval==='daily'?nextDailyDelay(config.syncConfig.dailyHour):intervalMs(config.syncConfig.interval);timer=setTimeout(async()=>{try{await performSync();}catch{}finally{await schedule();}},delay);}
function createWindow(){mainWindow=new BrowserWindow({width:1040,height:720,minWidth:880,minHeight:620,show:false,webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,nodeIntegration:false,sandbox:true}});mainWindow.webContents.once('did-finish-load',async()=>{const preloadReady=await mainWindow?.webContents.executeJavaScript(`typeof window.xmtAgent === 'object'`);console.log('renderer loaded, preload API:',preloadReady);});mainWindow.webContents.on('did-fail-load',(_event,code,description,url)=>console.error('renderer load failed:',{code,description,url}));const dev=process.env.ELECTRON_RENDERER_URL;if(dev)void mainWindow.loadURL(dev);else{const filePath=path.join(__dirname,'../renderer/index.html');console.log('loading renderer:',filePath);void mainWindow.loadFile(filePath);}mainWindow.once('ready-to-show',()=>mainWindow?.show());mainWindow.on('close',event=>{if(!(app as typeof app&{isQuitting?:boolean}).isQuitting){event.preventDefault();mainWindow?.hide();}});}
function createTray(){const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32"><rect rx="7" width="32" height="32" fill="#2563eb"/><path d="M8 9l16 14M24 9L8 23" stroke="white" stroke-width="4"/></svg>`;tray=new Tray(nativeImage.createFromDataURL(`data:image/svg+xml;base64,${Buffer.from(svg).toString('base64')}`).resize({width:16,height:16}));tray.setToolTip('XMT Creator Agent');tray.setContextMenu(Menu.buildFromTemplate([{label:'打开窗口',click:()=>{mainWindow?.show();mainWindow?.focus();}},{label:'立即同步',click:()=>void performSync().catch(()=>{})},{type:'separator'},{label:'退出',click:()=>{(app as typeof app&{isQuitting?:boolean}).isQuitting=true;app.quit();}}]));tray.on('double-click',()=>mainWindow?.show());}
ipcMain.handle('agent:get-state',()=>state());
ipcMain.handle('agent:setup',async(_event,input:SetupInput)=>{const serverUrl=input.serverUrl.replace(/\/$/,'');if(!/^https:\/\//i.test(serverUrl)&&!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/i.test(serverUrl))throw new Error('服务器地址必须使用 HTTPS');const session=await loginXmt(serverUrl,input.username,input.password);const deviceId=fingerprint();const bound=await register(serverUrl,session.token,input.accountId,deviceId);const config:AgentConfig={serverUrl,agentId:bound.agent_id,deviceId,platform:'douyin',accountId:input.accountId,accountName:input.accountId,browserConfig:{mode:'system_chrome',cdpEndpoint:'http://127.0.0.1:9222'},syncConfig:{enabled:false,interval:'manual',dailyHour:2}};await writeConfig(config);await saveToken(bound.agent_token);await log('XMT 连接与设备绑定成功');return emit();});
ipcMain.handle('agent:login-open',async()=>{if(activeLoginAdapter)throw new Error('浏览器登录流程已经打开');const config=await readConfig();if(!config)throw new Error('请先完成连接');activeLoginAdapter=browserAdapter(config);try{await activeLoginAdapter.openLogin();chromeConnected=true;douyinLoggedIn=false;await log(`已自动启动并连接 Chrome，浏览器模式 ${config.browserConfig.mode}`);await emit();}catch(error){activeLoginAdapter=null;chromeConnected=false;throw error;}});
ipcMain.handle('agent:login-complete',async()=>{if(!activeLoginAdapter)throw new Error('请先打开登录窗口');const loggedIn=await activeLoginAdapter.completeLogin();if(!loggedIn)throw new Error('未检测到有效的抖音创作者中心登录状态，请完成登录后重试。');douyinLoggedIn=true;activeLoginAdapter=null;await log('Chrome 已连接，抖音登录状态正常');return emit();});
ipcMain.handle('agent:sync',()=>performSync());
ipcMain.handle('agent:settings',async(_event,input:{serverUrl:string;enabled:boolean;interval:'manual'|'12h'|'daily';dailyHour:number;autoLaunch:boolean;browserMode:BrowserMode;chromePath?:string})=>{const config=await readConfig();if(!config)throw new Error('请先完成连接');config.serverUrl=input.serverUrl.replace(/\/$/,'');config.browserConfig={mode:input.browserMode,cdpEndpoint:'http://127.0.0.1:9222',chromePath:input.chromePath||undefined};config.syncConfig={enabled:input.enabled,interval:input.interval,dailyHour:Math.max(0,Math.min(23,Number(input.dailyHour)||2))};await writeConfig(config);if(!portableMode)app.setLoginItemSettings({openAtLogin:input.autoLaunch,path:process.execPath});await schedule();await log(`桌面设置已更新，浏览器模式 ${input.browserMode}，运行模式 ${portableMode?'portable':'standard'}`);return emit();});
ipcMain.handle('agent:choose-chrome',async()=>{const options:Electron.OpenDialogOptions={title:'选择 Google Chrome',defaultPath:'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',properties:['openFile'],filters:[{name:'Google Chrome',extensions:['exe']}]};const result=mainWindow?await dialog.showOpenDialog(mainWindow,options):await dialog.showOpenDialog(options);if(result.canceled||!result.filePaths[0])return null;const selected=result.filePaths[0];if(path.basename(selected).toLowerCase()!=='chrome.exe')throw new Error('请选择 chrome.exe');return selected;});
ipcMain.handle('agent:open-logs',async()=>{await fs.mkdir(paths().logs,{recursive:true});await shell.openPath(paths().logs);});
app.whenReady().then(async()=>{createWindow();createTray();await schedule();app.on('activate',()=>mainWindow?.show());});
app.on('window-all-closed',()=>{});app.on('before-quit',()=>{(app as typeof app&{isQuitting?:boolean}).isQuitting=true;if(timer)clearTimeout(timer);});
