import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {execFileSync} from 'node:child_process';
import {chromium,firefox,webkit} from 'playwright';import {capabilities} from './capabilities.js';import type{BrowserEngine,BrowserInfo,BrowserType}from'./types.js';
type Candidate={type:BrowserType;engine:BrowserEngine;name:string;path?:string;source:string};
export const macCandidates=(home:string):Candidate[]=>[
 ['chrome','Google Chrome','Google Chrome.app'],['chromium','Chromium','Chromium.app'],['edge','Microsoft Edge','Microsoft Edge.app'],['brave','Brave Browser','Brave Browser.app'],['arc','Arc','Arc.app'],
].flatMap(([type,name,bundle])=>['/Applications',path.join(home,'Applications')].map(root=>({type:type as BrowserType,engine:'chromium' as const,name,path:path.join(root,bundle,'Contents','MacOS',name),source:'macos-app'})));
export const windowsCandidates=(env:NodeJS.ProcessEnv):Candidate[]=>{const roots=[env.PROGRAMFILES,env['PROGRAMFILES(X86)'],env.LOCALAPPDATA].filter(Boolean) as string[];return roots.flatMap(root=>[
 {type:'chrome' as const,engine:'chromium' as const,name:'Google Chrome',path:path.win32.join(root,'Google','Chrome','Application','chrome.exe'),source:'windows-app'},
 {type:'edge' as const,engine:'chromium' as const,name:'Microsoft Edge',path:path.win32.join(root,'Microsoft','Edge','Application','msedge.exe'),source:'windows-app'},
 {type:'brave' as const,engine:'chromium' as const,name:'Brave Browser',path:path.win32.join(root,'BraveSoftware','Brave-Browser','Application','brave.exe'),source:'windows-app'},
]);};
function version(executable:string){try{return execFileSync(executable,['--version'],{encoding:'utf8',timeout:3000}).trim().replace(/\r?\n/g,' ');}catch{return undefined;}}
function managed(type:BrowserType,engine:BrowserEngine,name:string,executablePath:string):BrowserInfo{return{id:`playwright:${type}`,displayName:name,browserType:type,engine,runtime:'playwright',executablePath,version:version(executablePath),source:'playwright',capabilities:capabilities(engine,'playwright'),compatibilityStatus:engine==='chromium'?'not_tested':'partially_compatible',compatibilityReason:engine==='chromium'?'等待实机兼容性检测':'可启动，但抖音创作者中心功能可能受限'};}
export function discoverBrowsers(options:{platform?:NodeJS.Platform;env?:NodeJS.ProcessEnv;home?:string;customPath?:string}={}):BrowserInfo[]{const platform=options.platform||process.platform,env=options.env||process.env,home=options.home||os.homedir();const candidates=platform==='darwin'?macCandidates(home):platform==='win32'?windowsCandidates(env):[];if(options.customPath)candidates.unshift({type:'custom',engine:'chromium',name:'自定义浏览器',path:options.customPath,source:'user'});const found:BrowserInfo[]=[];const seen=new Set<string>();for(const item of candidates){if(!item.path||!fs.existsSync(item.path))continue;let real:string;try{real=fs.realpathSync(item.path);if(!fs.statSync(real).isFile())continue;fs.accessSync(real,fs.constants.X_OK);}catch{continue;}if(seen.has(real))continue;seen.add(real);found.push({id:`system:${item.type}:${Buffer.from(real).toString('base64url').slice(0,12)}`,displayName:item.name,browserType:item.type,engine:item.engine,runtime:'system',executablePath:real,version:version(real),source:item.source,capabilities:capabilities(item.engine,'system'),compatibilityStatus:'not_tested',compatibilityReason:'等待实机兼容性检测'});}for(const [type,engine,name,api] of [['chromium','chromium','Playwright Chromium',chromium],['firefox','firefox','Playwright Firefox',firefox],['webkit','webkit','Playwright WebKit',webkit]] as const){const executable=api.executablePath();if(fs.existsSync(executable)&&!seen.has(fs.realpathSync(executable)))found.push(managed(type,engine,name,executable));}return found;}
export function rankBrowsers(found:BrowserInfo[],preferredId?:string,lastSuccessfulId?:string){const typeScore:Record<BrowserType,number>={chrome:50,edge:45,brave:43,chromium:40,arc:35,firefox:20,webkit:10,custom:30};return [...found].sort((a,b)=>((b.id===preferredId?1000:b.id===lastSuccessfulId?800:0)+typeScore[b.browserType]+(b.compatibilityStatus==='compatible'?100:b.compatibilityStatus==='incompatible'?-500:0))-((a.id===preferredId?1000:a.id===lastSuccessfulId?800:0)+typeScore[a.browserType]+(a.compatibilityStatus==='compatible'?100:a.compatibilityStatus==='incompatible'?-500:0)));}
export function fallbackBrowsers(found:BrowserInfo[],preferredId?:string,lastSuccessfulId?:string,maxAttempts=3){return rankBrowsers(found,preferredId,lastSuccessfulId).filter(item=>item.compatibilityStatus!=='incompatible').slice(0,Math.max(1,Math.min(3,maxAttempts)));}
/** Creator Center is Chromium-only in the Scrapling collector; keep generic fallback semantics unchanged. */
export function creatorFallbackBrowsers(found:BrowserInfo[],preferredId?:string,lastSuccessfulId?:string,maxAttempts=3){return fallbackBrowsers(found,preferredId,lastSuccessfulId,maxAttempts).filter(item=>item.capabilities.supportsCreatorCenter);}
