import crypto from 'node:crypto';
import zlib from 'node:zlib';
import bcrypt from 'bcrypt';
import { execute, queryOne, runInTransaction } from '../database/utils.js';
import { creatorInsightService } from './creatorInsights.js';

type JsonRecord = Record<string, unknown>;
type AgentRow = { id: number; user_id: number; platform: string; account_id: string; token_hash: string };
const text = (value: unknown, fallback = '') => value == null ? fallback : String(value);
const number = (value: unknown) => Number.isFinite(Number(value)) ? Number(value) : 0;
const json = (value: unknown) => JSON.stringify(value ?? {});
const array = (value: unknown, max: number): JsonRecord[] => Array.isArray(value) ? value.filter((item): item is JsonRecord => Boolean(item) && typeof item === 'object').slice(0, max) : [];
const key = (token: string) => crypto.createHash('sha256').update(token).digest();
const canonical = (body: JsonRecord) => [body.agent_id, body.platform, body.account_id, body.collected_at, JSON.stringify(body.data)].join('\n');

async function openEnvelope(body: JsonRecord, authorization?: string) {
  const token = authorization?.match(/^Bearer\s+(.+)$/i)?.[1];
  const agent = await queryOne<AgentRow>('SELECT id,user_id,platform,account_id,token_hash FROM creator_agents WHERE id=?', [Number(body.agent_id)]);
  if (!token || !agent || !(await bcrypt.compare(token, agent.token_hash))) throw Object.assign(new Error('Agent 身份认证失败'), { statusCode: 401 });
  if (body.platform !== agent.platform || text(body.account_id) !== agent.account_id) throw Object.assign(new Error('Agent 设备或平台账号绑定不匹配'), { statusCode: 403 });
  const expected = crypto.createHmac('sha256', token).update(canonical(body)).digest('hex'); const supplied = text(body.signature);
  if (supplied.length !== expected.length || !crypto.timingSafeEqual(Buffer.from(expected), Buffer.from(supplied))) throw Object.assign(new Error('上传签名验证失败'), { statusCode: 401 });
  try { const envelope = body.data as {iv:string;tag:string;ciphertext:string}; const decipher = crypto.createDecipheriv('aes-256-gcm', key(token), Buffer.from(envelope.iv,'base64')); decipher.setAuthTag(Buffer.from(envelope.tag,'base64')); return { agent, payload: JSON.parse(decipher.update(envelope.ciphertext,'base64','utf8') + decipher.final('utf8')) as JsonRecord }; }
  catch { throw Object.assign(new Error('上传数据解密失败'), { statusCode: 400 }); }
}

export async function acceptCreatorDataSyncV291(body: JsonRecord, authorization?: string) {
  const { agent, payload } = await openEnvelope(body, authorization);
  if (payload.platform !== agent.platform) throw Object.assign(new Error('同步数据平台与 Agent 绑定不匹配'), { statusCode: 403 });
  const account = payload.account && typeof payload.account === 'object' ? payload.account as JsonRecord : {};
  const platformUid = text(account.platform_uid || account.uid || agent.account_id); if (platformUid !== agent.account_id) throw Object.assign(new Error('同步账号与 Agent 绑定不匹配'), { statusCode: 403 });
  const snapshotTime = text(body.collected_at, new Date().toISOString()); const syncTask = payload.sync_task && typeof payload.sync_task === 'object' ? payload.sync_task as JsonRecord : {};
  const taskId = text(syncTask.task_id, crypto.randomUUID());
  await execute(`INSERT INTO creator_sync_tasks(agent_id,task_id,start_time,platform,account,status) VALUES(?,?,?,?,?,'running') ON CONFLICT(agent_id,task_id) DO UPDATE SET status='running',start_time=excluded.start_time,end_time=NULL,error_message=NULL`, [agent.id, taskId, text(syncTask.start_time,snapshotTime), agent.platform, platformUid]);
  const modules:Record<string,'success'|'failed'>={account:'failed',works:'failed',metrics:'failed',trends:'failed',account_metrics:'failed',fans:'failed',raw:'failed',page_schema:'failed',insights:'failed'}; const errors:Record<string,string>={};
  const attempt = async (name:string, run:()=>Promise<void>) => { try { await run(); modules[name]='success'; } catch(error) { modules[name]='failed'; errors[name]=error instanceof Error?error.message:String(error); } };
  let accountId = 0;
  await attempt('account', async()=>runInTransaction(async tx=>{await tx.execute(`INSERT INTO creator_platform_accounts(user_id,platform,platform_uid,nickname,avatar,account_name,status,updated_at) VALUES(?,?,?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(user_id,platform,platform_uid) DO UPDATE SET nickname=excluded.nickname,avatar=excluded.avatar,account_name=excluded.account_name,status=excluded.status,updated_at=CURRENT_TIMESTAMP`,[agent.user_id,agent.platform,platformUid,text(account.nickname),text(account.avatar),text(account.account_name||account.nickname),text(account.status,'active')]);const row=await tx.queryOne<{id:number}>('SELECT id FROM creator_platform_accounts WHERE user_id=? AND platform=? AND platform_uid=?',[agent.user_id,agent.platform,platformUid]);if(!row)throw new Error('账号写入失败');accountId=row.id;await tx.execute(`INSERT INTO creator_account_access(account_id,user_id,access_level) VALUES(?,?,'manage') ON CONFLICT(account_id,user_id) DO UPDATE SET access_level='manage'`,[accountId,agent.user_id]);}));
  if (!accountId) { for(const name of Object.keys(modules).filter(name=>name!=='account')) errors[name]='账号模块失败，已跳过'; return finishTask(agent.id,taskId,modules,errors,snapshotTime,accountId); }
  const contents=array(payload.contents,5000),metrics=array(payload.metrics,20000),trends=array(payload.trends,50000),rawRecords=array(payload.raw_records,10000),schemas=array(payload.page_schemas,10000);
  await attempt('works',async()=>runInTransaction(async tx=>{for(const item of contents){const itemId=text(item.platform_item_id||item.item_id);if(!itemId)continue;await tx.execute(`INSERT INTO creator_content_items(account_id,platform,platform_item_id,title,cover_url,publish_time,duration,status,raw_json) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(account_id,platform,platform_item_id) DO UPDATE SET title=excluded.title,cover_url=excluded.cover_url,publish_time=excluded.publish_time,duration=excluded.duration,status=excluded.status,raw_json=excluded.raw_json`,[accountId,agent.platform,itemId,text(item.title),text(item.cover_url||item.cover),text(item.publish_time||item.published_at)||null,number(item.duration),text(item.status),json(item.raw_json??item)]);}}));
  await attempt('metrics',async()=>runInTransaction(async tx=>{for(const item of metrics){const row=await tx.queryOne<{id:number}>('SELECT id FROM creator_content_items WHERE account_id=? AND platform_item_id=?',[accountId,text(item.platform_item_id||item.item_id)]);if(!row)continue;await tx.execute(`INSERT INTO creator_content_metrics(content_id,snapshot_time,play_count,like_count,comment_count,share_count,favorite_count,play_duration,completion_rate,cover_click_rate,raw_json) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(content_id,snapshot_time) DO NOTHING`,[row.id,text(item.snapshot_time,snapshotTime),number(item.play_count),number(item.like_count),number(item.comment_count),number(item.share_count),number(item.favorite_count||item.collect_count),number(item.play_duration),number(item.completion_rate),number(item.cover_click_rate),json(item.raw_json??item)]);}}));
  await attempt('trends',async()=>runInTransaction(async tx=>{for(const item of trends){const row=await tx.queryOne<{id:number}>('SELECT id FROM creator_content_items WHERE account_id=? AND platform_item_id=?',[accountId,text(item.platform_item_id||item.item_id)]);if(row&&text(item.metric_name))await tx.execute('INSERT OR IGNORE INTO creator_content_trends(content_id,metric_name,metric_value,record_time) VALUES(?,?,?,?)',[row.id,text(item.metric_name),number(item.metric_value),text(item.record_time,snapshotTime)]);}}));
  const accountMetrics=payload.account_metrics&&typeof payload.account_metrics==='object'?payload.account_metrics as JsonRecord:{};
  await attempt('account_metrics',async()=>runInTransaction(async tx=>{await tx.execute(`INSERT INTO creator_account_metrics(account_id,snapshot_time,fans_count,play_count,interaction_count,profile_visit_count,growth_json,raw_json) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(account_id,snapshot_time) DO NOTHING`,[accountId,text(accountMetrics.snapshot_time,snapshotTime),number(accountMetrics.fans_count),number(accountMetrics.play_count),number(accountMetrics.interaction_count),number(accountMetrics.profile_visit_count),json(accountMetrics.growth_json),json(accountMetrics.raw_json??accountMetrics)]);}));
  const fansValid=payload.fans===undefined||(Boolean(payload.fans)&&typeof payload.fans==='object'&&!Array.isArray(payload.fans));const fans=fansValid&&payload.fans?payload.fans as JsonRecord:{};
  await attempt('fans',async()=>{if(!fansValid)throw new Error('fans 模块格式无效');await runInTransaction(async tx=>{if(Object.keys(fans).length)await tx.execute(`INSERT INTO creator_fans_portraits(account_id,snapshot_time,gender_json,age_json,city_json,province_json,interest_json,active_time_json,raw_json) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(account_id,snapshot_time) DO NOTHING`,[accountId,text(fans.snapshot_time,snapshotTime),json(fans.gender_json||fans.gender),json(fans.age_json||fans.age),json(fans.city_json||fans.city),json(fans.province_json||fans.province),json(fans.interest_json||fans.interest),json(fans.active_time_json||fans.active_time),json(fans.raw_json??fans)]);});});
  await attempt('raw',async()=>runInTransaction(async tx=>{for(const item of rawRecords){const raw=json(item.response_json??item.response);const hash=crypto.createHash('sha256').update([agent.platform,text(item.page_type||item.page),text(item.api_url||item.url),text(item.method,'GET'),raw].join('\n')).digest('hex');const compressed=zlib.gzipSync(raw).toString('base64');await tx.execute(`INSERT OR IGNORE INTO creator_api_raw_records(user_id,agent_id,platform,page_type,api_url,method,response_json,created_at,hash,compression) VALUES(?,?,?,?,?,?,?,?,?,'gzip')`,[agent.user_id,agent.id,agent.platform,text(item.page_type||item.page,'unknown'),text(item.api_url||item.url),text(item.method,'GET').toUpperCase(),compressed,text(item.created_at||item.captured_at,snapshotTime),hash]);}}));
  await attempt('page_schema',async()=>runInTransaction(async tx=>{for(const item of schemas)await tx.execute(`INSERT INTO creator_page_schema(page,tab,api,fields,updated_at) VALUES(?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(page,tab,api) DO UPDATE SET fields=excluded.fields,updated_at=CURRENT_TIMESTAMP`,[text(item.page),text(item.tab),text(item.api),json(item.fields)]);}));
  await attempt('insights',async()=>{await creatorInsightService.generate(accountId);});
  await execute('UPDATE creator_agents SET last_active_at=CURRENT_TIMESTAMP WHERE id=?',[agent.id]);
  return finishTask(agent.id,taskId,modules,errors,snapshotTime,accountId,{contents:contents.length,metrics:metrics.length,trends:trends.length,raw_records:rawRecords.length});
}

async function finishTask(agentId:number,taskId:string,modules:Record<string,'success'|'failed'>,errors:Record<string,string>,snapshotTime:string,accountId:number,counts:JsonRecord={}){const successCount=Object.values(modules).filter(v=>v==='success').length;const failedCount=Object.keys(modules).length-successCount;const status=failedCount===0?'success':successCount===0?'failed':'partial_success';await execute('UPDATE creator_sync_tasks SET end_time=CURRENT_TIMESTAMP,status=?,success_count=?,failed_count=?,error_message=?,module_status_json=? WHERE agent_id=? AND task_id=?',[status,successCount,failedCount,Object.values(errors).join('; ')||null,JSON.stringify(modules),agentId,taskId]);return{success:successCount>0,status,success_count:successCount,failed_count:failedCount,modules,errors,snapshot_time:snapshotTime,account_id:accountId,...counts};}
