import assert from 'node:assert/strict';
import test from 'node:test';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { inspectCoverMetadata, parseCoverMetadataSummary } from './coverMetadata.js';

const accountId='fixture-account';
const hash=crypto.createHash('sha256').update(accountId).digest('hex');
const summary={account_scope_hash:hash,collected_at:'2026-09-01T00:00:00.000Z',execution_status:'completed',termination_reason:'completed',diagnostics:[{stage:'source_discovery',status:'ok',count:1,duration_bucket:'lt_1m',boolean:true},{stage:'termination',status:'ok',count:2,termination_reason:'completed',duration_bucket:'lt_1m',boolean:true}],works_seen:2,works_with_candidates:1,works_without_candidates:1,candidates_seen:2,probe_summary:{valid_images:1,forbidden:0,not_found:0,non_image:0,timeout:0,invalid_url:0,signed:2,expiring:1,expired_at_collection:0}};
test('cover metadata bridge only accepts a scrubbed aggregate summary',()=>{assert.equal(parseCoverMetadataSummary(summary,accountId).works_seen,2);for(const secret of ['url','token','cookie','work_id','account_id','unknown'])assert.throws(()=>parseCoverMetadataSummary({...summary,[secret]:'sensitive-value'},accountId),/UNSAFE/);assert.throws(()=>parseCoverMetadataSummary({...summary,account_scope_hash:'0'.repeat(64)},accountId),/SCOPE_MISMATCH/);});
test('metadata-only call graph does not invoke upload collaborators',async()=>{let requests=0,shutdowns=0;const result=await inspectCoverMetadata({config:{platform:'douyin',accountId,agentId:1,deviceId:'d',accountName:'a',serverUrl:'https://production.invalid',browserConfig:{} as never,syncConfig:{enabled:false,interval:'manual',dailyHour:2}},profilePath:'/fixture/profile',browser:{engine:'chromium'},bridge:{runtime:()=>({available:true,code:'READY',mode:'packaged-worker',collector:'fixture'}),request:async(method,params)=>{requests++;assert.equal(method,'cover_metadata_only');assert.equal(params.accountId,undefined);assert.equal(params.accountScopeHash,hash);return {data:summary};},shutdown:async()=>{shutdowns++;}}});assert.equal(result.candidates_seen,2);assert.equal(requests,1);assert.equal(shutdowns,1);});
test('worker failures terminate the dedicated bridge and never invoke a sync callback',async()=>{let bridgeCalls=0, shutdowns=0, normalSyncCalls=0;const secret='https://signed.example/cover?token=secret-cookie';const normalSync=()=>{normalSyncCalls++;};await assert.rejects(()=>inspectCoverMetadata({config:{platform:'douyin',accountId,agentId:1,deviceId:'d',accountName:'a',serverUrl:'https://production.invalid',browserConfig:{} as never,syncConfig:{enabled:false,interval:'manual',dailyHour:2}},profilePath:'/fixture/profile',browser:{},bridge:{runtime:()=>({available:true,code:'READY',mode:'packaged-worker',collector:'fixture'}),request:async()=>{bridgeCalls++;throw new Error(secret);},shutdown:async()=>{shutdowns++;}}}));assert.equal(bridgeCalls,1);assert.equal(shutdowns,1);assert.equal(normalSyncCalls,0);void normalSync;});
test('metadata-only implementation has no forbidden runtime import',()=>{const source=fs.readFileSync(path.join(process.cwd(),'core/collector/coverMetadata.ts'),'utf8');for(const forbidden of ["from '../uploader", "from '../database", "from './taskRunner", "from '../scheduler"])assert.equal(source.includes(forbidden),false,forbidden);});
test('source-not-found is a safe failed diagnostic, never a successful zero result',()=>{const failure={...summary,execution_status:'failed',termination_reason:'source_not_found',diagnostics:[{stage:'termination',status:'failed',count:0,code:'COVER_METADATA_SOURCE_NOT_FOUND',termination_reason:'source_not_found',duration_bucket:'unknown',boolean:false}],works_seen:0,works_with_candidates:0,works_without_candidates:0,candidates_seen:0};const parsed=parseCoverMetadataSummary(failure,accountId);assert.equal(parsed.execution_status,'failed');assert.equal(parsed.diagnostics[0]?.code,'COVER_METADATA_SOURCE_NOT_FOUND');assert.throws(()=>parseCoverMetadataSummary({...failure,diagnostics:[{...failure.diagnostics[0],url:'https://secret.invalid'}]},accountId),/UNSAFE/);});
