import { execute, executeInsert, queryAll, queryOne } from '../../database/utils.js';
import { decryptToken } from './token.service.js';
import { fetchAuthorizedUserProfile } from './user.service.js';
import { fetchAuthorizedVideos, fetchVideoStatistics, type RemoteVideo } from './video.service.js';

type Account = { id: number; open_id: string; access_token_encrypt: string };
export async function recordSync(accountId: number | null, syncType: string, status: string, message: string) { await execute(`INSERT INTO douyin_sync_logs (account_id, sync_type, status, message) VALUES (?, ?, ?, ?)`, [accountId, syncType, status, message]); }
async function account(id: number) { const row = await queryOne<Account>('SELECT id, open_id, access_token_encrypt FROM douyin_accounts WHERE id=? AND status="active"', [id]); if (!row?.access_token_encrypt) throw new Error('未找到有效的抖音授权账号'); return { ...row, accessToken: decryptToken(row.access_token_encrypt) }; }
const metric = (video: RemoteVideo, key: string) => Number(video.statistics?.[key] ?? video[key as keyof RemoteVideo] ?? 0);
export async function syncAccount(id: number) { const item = await account(id); try { const profile = await fetchAuthorizedUserProfile(item.accessToken, item.open_id); await execute(`UPDATE douyin_accounts SET nickname=?, avatar=?, union_id=COALESCE(?, union_id), updated_at=CURRENT_TIMESTAMP WHERE id=?`, [profile.nickname ?? null, profile.avatar ?? null, profile.union_id ?? null, id]); await execute(`INSERT OR REPLACE INTO douyin_account_statistics (account_id, fans_count, following_count, video_count, snapshot_date) VALUES (?, ?, ?, ?, date('now'))`, [id, Number((profile as Record<string, unknown>).fans_count ?? 0), Number((profile as Record<string, unknown>).following_count ?? 0), Number((profile as Record<string, unknown>).video_count ?? 0)]); await recordSync(id, 'account', 'success', '已同步抖音账号公开信息'); return profile; } catch (error) { await recordSync(id, 'account', 'failed', (error as Error).message); throw error; } }
export async function syncVideos(id: number) { const item = await account(id); try { const videos = await fetchAuthorizedVideos(item.accessToken, item.open_id); for (const video of videos) { if (!video.item_id) continue; await execute(`INSERT INTO douyin_videos (account_id,item_id,title,cover,share_url,publish_time,play_count,like_count,comment_count,share_count,collect_count,sync_time,raw_data,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(account_id,item_id) DO UPDATE SET title=excluded.title,cover=excluded.cover,share_url=excluded.share_url,publish_time=excluded.publish_time,play_count=excluded.play_count,like_count=excluded.like_count,comment_count=excluded.comment_count,share_count=excluded.share_count,collect_count=excluded.collect_count,sync_time=excluded.sync_time,raw_data=excluded.raw_data,updated_at=CURRENT_TIMESTAMP`, [id, video.item_id, video.title ?? null, video.cover ?? null, video.share_url ?? null, video.create_time ? new Date(video.create_time * 1000).toISOString() : null, metric(video,'play_count'), metric(video,'like_count'), metric(video,'comment_count'), metric(video,'share_count'), metric(video,'collect_count'), new Date().toISOString(), JSON.stringify(video)]); } await recordSync(id, 'videos', 'success', `已同步 ${videos.length} 条视频`); return { count: videos.length }; } catch (error) { await recordSync(id, 'videos', 'failed', (error as Error).message); throw error; } }
export async function syncStatistics(id: number) { const item = await account(id); try { const videos = await queryAll<{ id:number; item_id:string }>('SELECT id,item_id FROM douyin_videos WHERE account_id=?', [id]); const data = await fetchVideoStatistics(item.accessToken, item.open_id, videos.map((v) => v.item_id)); const ids = new Map(videos.map((v) => [v.item_id, v.id])); for (const video of data) { const videoId = ids.get(video.item_id); if (!videoId) continue; await execute(`INSERT OR REPLACE INTO douyin_video_statistics (video_id,play_count,like_count,comment_count,share_count,collect_count,snapshot_date) VALUES (?,?,?,?,?,?,date('now'))`, [videoId, metric(video,'play_count'), metric(video,'like_count'), metric(video,'comment_count'), metric(video,'share_count'), metric(video,'collect_count')]); } await recordSync(id, 'statistics', 'success', `已同步 ${data.length} 条视频统计`); return { count: data.length }; } catch (error) { await recordSync(id, 'statistics', 'failed', (error as Error).message); throw error; } }
export async function requestSync(accountId: number, syncType = 'full') { if (syncType === 'account') return syncAccount(accountId); if (syncType === 'videos') return syncVideos(accountId); if (syncType === 'statistics') return syncStatistics(accountId); const result = await Promise.all([syncAccount(accountId), syncVideos(accountId)]); await syncStatistics(accountId); return { status: 'success', accountId, result }; }
