import { useCallback, useEffect, useState, type ReactNode } from 'react';
import { Activity, Heart, MousePointer2, Play, RefreshCw, Sparkles, Users, type LucideIcon } from 'lucide-react';
import { getCreatorCenterData, type CreatorCenterData } from '@/api/creatorCenter';

export type JsonRecord=Record<string,unknown>;
export const asRecord=(value:unknown):JsonRecord=>value&&typeof value==='object'&&!Array.isArray(value)?value as JsonRecord:{};
export const num=(value:unknown)=>{const result=Number(value);return Number.isFinite(result)?result:0;};
export const formatNumber=(value:unknown)=>new Intl.NumberFormat('zh-CN',{notation:num(value)>=10000?'compact':'standard',maximumFractionDigits:1}).format(num(value));
export const formatPercent=(value:unknown)=>`${num(value).toFixed(2)}%`;
export const formatDate=(value:unknown,full=false)=>value?new Date(String(value)).toLocaleString('zh-CN',full?{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}:{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'—';
export const levelMeta={viral:{label:'爆款',className:'bg-rose-500/12 text-rose-500'},excellent:{label:'优秀',className:'bg-emerald-500/12 text-emerald-500'},normal:{label:'普通',className:'bg-blue-500/12 text-blue-500'},low:{label:'低效',className:'bg-slate-500/12 text-studio-text-muted'}} as const;

export function useCreatorData(){const[data,setData]=useState<CreatorCenterData|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const load=useCallback(async()=>{setLoading(true);setError('');try{setData(await getCreatorCenterData());}catch(cause){setError(cause instanceof Error?cause.message:'数据加载失败');}finally{setLoading(false);}},[]);useEffect(()=>{void load();},[load]);return{data,loading,error,load};}
export function PageHeader({title,description,loading,onRefresh,actions}:{title:string;description:string;loading?:boolean;onRefresh?:()=>void;actions?:ReactNode}){return <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="text-3xl font-semibold tracking-tight text-studio-text">{title}</h1><p className="mt-2 text-sm text-studio-text-muted">{description}</p></div><div className="flex flex-wrap gap-2">{actions}{onRefresh?<button type="button" onClick={onRefresh} disabled={loading} className="inline-flex h-10 items-center justify-center gap-2 rounded-lg border border-studio-border bg-studio-card px-4 text-sm font-medium transition hover:border-studio-cyan/60 disabled:opacity-60"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/>刷新数据</button>:null}</div></header>}
export function Panel({title,description,children,className=''}:{title:string;description?:string;children:ReactNode;className?:string}){return <section className={`rounded-2xl border border-studio-border bg-studio-card p-5 ${className}`}><h2 className="font-semibold">{title}</h2>{description?<p className="mt-1 text-xs text-studio-text-muted">{description}</p>:null}<div className="mt-5">{children}</div></section>}
const accents={cyan:'bg-cyan-500/10 text-cyan-500',blue:'bg-blue-500/10 text-blue-500',rose:'bg-rose-500/10 text-rose-500',violet:'bg-violet-500/10 text-violet-500',emerald:'bg-emerald-500/10 text-emerald-500'};
export function MetricCard({label,value,icon:Icon,accent='cyan',hint}:{label:string;value:unknown;icon:LucideIcon;accent?:keyof typeof accents;hint?:string}){return <article className="rounded-2xl border border-studio-border bg-studio-card p-5"><div className="flex items-center justify-between"><span className="text-sm text-studio-text-muted">{label}</span><span className={`grid h-9 w-9 place-items-center rounded-xl ${accents[accent]}`}><Icon className="h-4 w-4"/></span></div><p className="mt-5 text-3xl font-semibold tracking-tight">{typeof value==='string'?value:formatNumber(value)}</p>{hint?<p className="mt-2 text-xs text-studio-text-muted">{hint}</p>:null}</article>}
export function LineChart({values,color='rgb(6 182 212)',height='h-52'}:{values:number[];color?:string;height?:string}){const safe=values.length>1?values:[values[0]||0,values[0]||0];const min=Math.min(...safe),max=Math.max(...safe),range=max-min||1;const points=safe.map((value,index)=>`${(index/(safe.length-1))*100},${94-((value-min)/range)*78}`).join(' ');return <div className={height}><svg viewBox="0 0 100 100" preserveAspectRatio="none" className="h-full w-full overflow-visible" role="img" aria-label="数据趋势折线图"><path d={`M ${points} L 100 100 L 0 100 Z`} fill={color} opacity=".1"/><polyline points={points} fill="none" stroke={color} strokeWidth="2" vectorEffect="non-scaling-stroke" strokeLinejoin="round"/></svg></div>}
export function SegmentBar({items}:{items:Array<{label:string;value:number;color?:string}>}){const total=items.reduce((sum,item)=>sum+item.value,0)||1;return <div><div className="flex h-3 overflow-hidden rounded-full bg-studio-surface">{items.map((item,index)=><span key={item.label} style={{width:`${item.value/total*100}%`,backgroundColor:item.color||`hsl(${188+index*38} 75% 52%)`}}/>)}</div><div className="mt-4 grid gap-2 sm:grid-cols-2">{items.map((item,index)=><div key={item.label} className="flex items-center justify-between text-sm"><span className="flex items-center gap-2 text-studio-text-muted"><i className="h-2.5 w-2.5 rounded-full" style={{backgroundColor:item.color||`hsl(${188+index*38} 75% 52%)`}}/>{item.label}</span><b>{formatNumber(item.value)}</b></div>)}</div></div>}
export function AccountHeader({account}:{account:JsonRecord}){return <section className="flex items-center gap-4 rounded-2xl border border-studio-border bg-gradient-to-r from-studio-card to-studio-surface p-5">{account.avatar?<img src={String(account.avatar)} alt="账号头像" className="h-14 w-14 rounded-full object-cover ring-2 ring-studio-cyan/30"/>:<div className="grid h-14 w-14 place-items-center rounded-full bg-studio-cyan/10 text-studio-cyan"><Sparkles className="h-6 w-6"/></div>}<div className="min-w-0"><h2 className="truncate text-lg font-semibold">{String(account.nickname||account.account_name||'抖音账号')}</h2><p className="mt-1 text-sm text-studio-text-muted">抖音 UID：{String(account.douyin_uid||account.account_id||account.platform_uid||'—')}</p></div><span className="ml-auto rounded-full bg-emerald-500/10 px-3 py-1 text-xs font-medium text-emerald-500">真实数据已入库</span></section>}
export function LoadingState(){return <div className="grid min-h-[360px] place-items-center rounded-2xl border border-studio-border bg-studio-card"><RefreshCw className="h-7 w-7 animate-spin text-studio-cyan"/></div>}
export function ErrorState({message}:{message:string}){return <div className="rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-500">{message}</div>}
export function EmptyState({title='等待首个真实数据快照'}:{title?:string}){return <div className="grid min-h-[360px] place-items-center rounded-2xl border border-dashed border-studio-border bg-studio-card"><div className="max-w-sm text-center"><Play className="mx-auto h-9 w-9 text-studio-text-muted"/><h2 className="mt-4 font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-studio-text-muted">请先通过 Creator Agent 完成抖音数据同步。分析中心只使用已入库的真实数据。</p></div></div>}
export const coreMetricIcons={plays:Play,likes:Heart,interactions:Activity,fans:Users,visits:MousePointer2};
