import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';

const script = fs.readFileSync(path.resolve('deploy/xmt-safe-deploy.sh'), 'utf8');
assert.match(script, /require_command sqlite3/);
assert.match(script, /sqlite3 "\$DB_PATH" "\.backup/);
assert.match(script, /PRAGMA quick_check/);
assert.match(script, /mkdir -m 0700 "\$lock_directory"/);
assert.match(script, /printf '%s:%s\\n' "\$\$"/);
assert.match(script, /PREVIOUS_SHA="\$\(git rev-parse HEAD\)"/);
assert.match(script, /TARGET_SHA_EXPECTED/);
assert.match(script, /Target branch does not match TARGET_SHA_EXPECTED/);
assert.match(script, /Checked-out target does not match TARGET_SHA_EXPECTED/);
assert.match(script, /trap rollback_code ERR/);
assert.match(script, /git checkout --detach "\$PREVIOUS_SHA"/);
assert.match(script, /rollback_code 1/);
assert.match(script, /Installing target dependencies without restarting the live application/);
assert.match(script, /restore_worktree_without_restart/);
assert.match(script, /npm ci; then restore_worktree_without_restart/);
assert.ok(script.indexOf('npm ci; then restore_worktree_without_restart') < script.indexOf('npm run migration:check'), 'target dependencies install before migration gate');
assert.ok(script.indexOf('npm run version:check') < script.indexOf('ops:backup-restore-drill'), 'version gate before restore drill');
assert.ok(script.indexOf('ops:backup-restore-drill') < script.indexOf('npm run migration:check'), 'restore drill before migration gate');
assert.ok(script.indexOf('npm run migration:check') < script.lastIndexOf('pm2 restart'), 'migration gate before the target PM2 restart');
assert.match(script, /Production requires XMT_RUNTIME_ENV_FILE/);
assert.ok(script.indexOf('ops:runtime-env-check') < script.lastIndexOf('pm2 restart'), 'runtime env gate before PM2 restart');
assert.ok(script.indexOf('ops:runtime-env-readback') > script.lastIndexOf('pm2 restart'), 'runtime readback after PM2 restart');
assert.ok(script.indexOf('ops:internal-exposure-check') > script.lastIndexOf('pm2 restart'), 'public internal gate after PM2 restart');
assert.doesNotMatch(script, /cp -p "\$DB_PATH"/);
console.log('safe deploy hardening static tests passed');
