import { useCallback, useEffect, useState } from 'react';
import { BarChart3, Link2, RefreshCw, Video } from 'lucide-react';
import { useParams } from 'react-router-dom';
import { getDouyinAnalysis, getOpenDouyinAccounts, getOpenDouyinStatistics, getOpenDouyinVideos, startDouyinBinding, syncDouyin, type DouyinAccount, type DouyinStatistics } from '@/api/douyinOpenPlatform';

const tabs = ['账号管理', '数据看板', '内容分析', '运营复盘', '报告中心'];
const number = (value?: number) => new Intl.NumberFormat('zh-CN').format(value || 0);
export default function DouyinOperationsCenter() {
  const { section } = useParams(); const tabBySection: Record<string, string> = { accounts: '账号管理', dashboard: '数据看板', content: '内容分析', retrospective: '运营复盘', reports: '报告中心' }; const [tab, setTab] = useState(tabBySection[section || ''] || '账号管理'); const [accounts, setAccounts] = useState<DouyinAccount[]>([]); const [statistics, setStatistics] = useState<DouyinStatistics>(); const [videos, setVideos] = useState<Array<Record<string, unknown>>>([]); const [analysis, setAnalysis] = useState<{ top10: Array<{ title: string; play_count: number; engagement_rate: number }>; best_publishing_hours: Array<{ hour: number; average_play_count: number }> }>(); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  useEffect(() => { setTab(tabBySection[section || ''] || '账号管理'); }, [section]);
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [accountRows, stats, videoRows, analysisResult] = await Promise.all([getOpenDouyinAccounts(), getOpenDouyinStatistics(), getOpenDouyinVideos(), getDouyinAnalysis()]); setAccounts(accountRows); setStatistics(stats); setVideos(videoRows); setAnalysis(analysisResult); } catch (cause) { setError(cause instanceof Error ? cause.message : '加载失败'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const bind = async () => { try { const { authorization_url } = await startDouyinBinding(); window.location.assign(authorization_url); } catch (cause) { setError(cause instanceof Error ? cause.message : '无法发起授权'); } };
  return <div className="space-y-6 p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm text-studio-text-muted">抖音开放平台中心</p><h1 className="text-2xl font-semibold text-studio-text">抖音运营中心</h1><p className="mt-1 text-sm text-studio-text-muted">仅使用已授权的 OpenAPI 数据；应用审核完成前不会抓取网页或填充模拟数据。</p></div><button onClick={bind} className="rounded-lg bg-studio-primary px-4 py-2 text-sm font-medium text-white"><Link2 className="mr-2 inline h-4 w-4" />绑定抖音账号</button></div>
    <div className="flex flex-wrap gap-2">{tabs.map((item) => <button key={item} onClick={() => setTab(item)} className={`rounded-full px-4 py-2 text-sm ${tab === item ? 'bg-studio-primary text-white' : 'bg-studio-card text-studio-text-muted'}`}>{item}</button>)}</div>
    {error && <div className="rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-400">{error}</div>}
    {tab === '账号管理' && <section className="rounded-xl border border-studio-border bg-studio-card p-5"><h2 className="mb-4 font-medium">已授权账号</h2>{loading ? '正在加载…' : accounts.length === 0 ? <p className="text-sm text-studio-text-muted">暂无已授权账号。审核通过并配置回调地址后，可在此绑定。</p> : <div className="space-y-3">{accounts.map((account) => <div key={account.id} className="flex justify-between rounded-lg bg-studio-surface p-4"><span>{account.nickname || account.open_id}</span><span className="text-sm text-studio-text-muted">{account.status} · 最近同步：{account.last_sync_at || '尚未同步'}</span><button onClick={() => void syncDouyin(account.id)} className="text-studio-cyan"><RefreshCw className="inline h-4 w-4" /> 同步</button></div>)}</div>}</section>}
    {tab === '数据看板' && <section className="grid gap-4 md:grid-cols-4">{[['已授权账号', statistics?.account_count, Link2], ['视频数量', statistics?.video_count, Video], ['累计播放', statistics?.play_count, BarChart3], ['平均互动率', statistics?.play_count ? ((statistics.like_count + statistics.comment_count + statistics.share_count) / statistics.play_count * 100).toFixed(2) + '%' : '—', BarChart3]].map(([label, value, Icon]) => { const C = Icon as typeof BarChart3; const displayValue = typeof value === 'number' ? number(value) : typeof value === 'string' ? value : '—'; return <div key={String(label)} className="rounded-xl border border-studio-border bg-studio-card p-5"><C className="h-5 w-5 text-studio-cyan" /><p className="mt-4 text-2xl font-semibold">{displayValue}</p><p className="text-sm text-studio-text-muted">{String(label)}</p></div>; })}<div className="md:col-span-2 rounded-xl border border-studio-border bg-studio-card p-5"><h2 className="font-medium">爆款内容 TOP10</h2><p className="mt-3 text-sm text-studio-text-muted">{analysis?.top10[0] ? `${analysis.top10[0].title} · ${number(analysis.top10[0].play_count)} 播放` : '首次真实同步后生成排行'}</p></div><div className="md:col-span-2 rounded-xl border border-studio-border bg-studio-card p-5"><h2 className="font-medium">最佳发布时间</h2><p className="mt-3 text-sm text-studio-text-muted">{analysis?.best_publishing_hours[0] ? `${analysis.best_publishing_hours[0].hour}:00` : '历史快照积累后生成'}</p></div></section>}
    {tab === '内容分析' && <section className="rounded-xl border border-studio-border bg-studio-card p-5"><h2 className="mb-4 font-medium">视频效果</h2>{videos.length === 0 ? <p className="text-sm text-studio-text-muted">暂无 OpenAPI 同步的视频数据。</p> : <div className="space-y-2">{videos.map((video) => <div key={String(video.id)} className="flex justify-between border-b border-studio-border py-3"><span>{String(video.title || '未命名视频')}</span><span>{number(Number(video.play_count))} 播放 · {number(Number(video.like_count))} 点赞</span></div>)}</div>}</section>}
    {(tab === '运营复盘' || tab === '报告中心') && <section className="rounded-xl border border-studio-border bg-studio-card p-6"><h2 className="font-medium">{tab}</h2><p className="mt-2 text-sm text-studio-text-muted">已接入 OpenAPI 视频排行、互动率和发布时间分析；AI 分析接口仅返回预留能力，不接入模型。日报将使用已同步的真实数据汇总新增作品、播放增长、热门与异常内容。</p></section>}
  </div>;
}
