import { useAuthStore } from '@/store';
export type CreatorTrend={content_id:number;metric_name:string;metric_value:number;record_time:string};
export type CreatorHealth={score:number;content_activity:number;fan_growth_rate:number;interaction_rate:number;content_stability:number;basis:Record<string,string>};
export type CreatorRatedWork={id:number;title:string;score:number;level:'viral'|'excellent'|'normal'|'low';engagement_rate:number;completion_rate:number;fans_gained:number};
export type CreatorCenterData={account:(Record<string,unknown>&{account_id:string;snapshot_time:string;source:string})|null;works:Array<Record<string,unknown>>;dashboard:Record<string,unknown>|null;fans:Record<string,unknown>|null;history:Array<{snapshot_time:string;source:string;fans_count?:number;play_count?:number;interaction_count?:number;profile_visit_count?:number}>;trends?:CreatorTrend[];insights?:Record<string,Record<string,unknown>>;analytics?:{health?:CreatorHealth;levels?:Record<string,number>;rated_works?:CreatorRatedWork[]};access_level?:'view'|'manage';data_sources:string[]};
export async function getCreatorCenterData(accountId?:string):Promise<CreatorCenterData>{const token=useAuthStore.getState().token;const query=accountId?`?account_id=${encodeURIComponent(accountId)}`:'';const response=await fetch(`/api/creator-agent/data${query}`,{headers:token?{Authorization:`Bearer ${token}`}:{}});if(!response.ok)throw new Error('创作者中心数据加载失败');return response.json();}

export type CreatorWorkAnalysis={score:number;level:CreatorRatedWork['level'];engagement_rate:number;completion_rate:number;fans_gained:number;average_play_duration:number;period:'24h'|'7d'|'30d';rules:Record<string,unknown>;trend:Array<{time:string;plays:number;interactions:number;fans:number}>;comments:{count:number;hot_words:Array<{word:string;count:number}>;keywords:Array<{word:string;count:number}>;feedback:Array<{label:string;count:number}>;samples:string[]};traffic:{recommendation:number;search:number;following:number;other:number};work:{id:number;platform_item_id:string;title:string;cover_url:string;publish_time:string;duration:number;tags:string[];url:string;metrics:{plays:number;likes:number;comments:number;shares:number;favorites:number;completion_rate:number;average_play_duration:number;fans_gained:number}}};
export type CreatorTrendSeries={period:'7d'|'30d'|'90d';days:number;series:Record<'plays'|'fans'|'interactions'|'publishes',Array<{time:string;value:number}>>};
export type CreatorFansAnalysis={compare_days:number;current:Record<string,unknown>|null;previous:Record<string,unknown>|null};
export type CreatorReport={id:number;type:'daily'|'weekly'|'monthly';created_at:string;content:Record<string,unknown>};
const authHeaders=()=>{const headers=new Headers({'Content-Type':'application/json'});const token=useAuthStore.getState().token;if(token)headers.set('Authorization',`Bearer ${token}`);return headers;};
async function creatorJson<T>(path:string,init?:RequestInit):Promise<T>{const headers=authHeaders();new Headers(init?.headers).forEach((value,key)=>headers.set(key,value));const response=await fetch(`/api/creator-agent${path}`,{...init,headers});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(String(body.message||'创作者分析请求失败'));}return response.json();}
export const getCreatorWorkAnalysis=(id:string,period:'24h'|'7d'|'30d')=>creatorJson<CreatorWorkAnalysis>(`/works/${encodeURIComponent(id)}/analysis?period=${period}`);
export const getCreatorTrends=(period:'7d'|'30d'|'90d')=>creatorJson<CreatorTrendSeries>(`/trends?period=${period}`);
export const getCreatorFansAnalysis=(compareDays=30)=>creatorJson<CreatorFansAnalysis>(`/fans-analysis?compare_days=${compareDays}`);
export const getCreatorReports=()=>creatorJson<CreatorReport[]>('/reports');
export const generateCreatorReport=(type:'daily'|'weekly'|'monthly',accountId:string)=>creatorJson<Record<string,unknown>>('/reports/generate',{method:'POST',body:JSON.stringify({type,account_id:accountId})});
