import fs from 'node:fs';
import { assessVersionGovernance } from './version-governance.mjs';
const root = new URL('../', import.meta.url);
const read = (file) => fs.readFileSync(new URL(file, root), 'utf8');
const pkg = JSON.parse(read('package.json')); const lock = JSON.parse(read('package-lock.json'));
const version = pkg.version;
const errors = assessVersionGovernance({ version, lock, read });
if (errors.length) throw new Error(errors.join('; '));
const agentPackage = JSON.parse(read('agent/package.json')); const agentVersion = JSON.parse(read('agent/version.json')).version;
if (agentPackage.version !== agentVersion || !/^\d+\.\d+\.\d+-agent$/.test(agentVersion)) throw new Error('Creator Agent 独立版本不一致或格式错误');
console.log(`版本一致：v${version}`);
