import React, { useState } from 'react';
import type { DesktopState } from '../types';
import type { SyncResult } from '../../core/types';
import type { CoverMetadataSummary } from '../../core/collector/coverMetadata';
import { loginActionError } from '../loginState';

export default function Dashboard({state,onLogin,onLoginComplete,onSync,onInspectCoverMetadata}:{state:DesktopState;onLogin:()=>Promise<unknown>;onLoginComplete:()=>Promise<unknown>;onSync:(sample?:boolean)=>Promise<SyncResult>;onInspectCoverMetadata:()=>Promise<CoverMetadataSummary>}) {
  const [result,setResult]=useState<SyncResult>(); const [cover,setCover]=useState<CoverMetadataSummary>(); const [actionError,setActionError]=useState(''); const [inspecting,setInspecting]=useState(false);
  const run=async(action:()=>Promise<unknown>,login=false)=>{setActionError('');try{return await action();}catch(cause){setActionError(login?loginActionError(cause):'操作未完成，请检查 Agent 诊断后重试。');}};
  const inspect=async()=>{setInspecting(true);setActionError('');try{setCover(await onInspectCoverMetadata());}catch{setActionError('封面来源检查未完成，请根据安全门禁或诊断后重试。');}finally{setInspecting(false);}};
  const identity=state.runtimeIdentity,capability=state.capabilities,loginLabel=capability.loginAction==='relogin'?'重新登录':capability.loginAction==='confirm'?'我已完成登录':'打开登录窗口';
  const account=state.account, canInspect=account.scope_status==='confirmed'&&!inspecting&&!state.syncing;
  return <div className="dashboard"><section className="hero card"><div><span className={`status ${state.connected?'online':'offline'}`}>{state.connected?'● 已连接':'● 未连接'}</span><h2>{account.is_bound?`已绑定${account.platform_label}账号`:'尚未绑定抖音账号'}</h2><p>{account.is_bound?`审计标识 ${account.account_audit_tag} · 范围${account.scope_status==='confirmed'?'已确认':'待确认'}`:'请完成账号绑定'}</p></div><div className="hero-meta"><span>当前浏览器</span><strong>{state.currentBrowser?.displayName||'未选择（请在设置中选择受支持浏览器）'}</strong></div></section>{actionError?<div className="error">{actionError}</div>:null}<section className="actions"><div className="card action"><div className="icon">抖</div><h3>登录抖音</h3><p>Agent 使用独立浏览器资料打开创作者中心，不影响日常浏览器。</p><div className="connection-checks"><span className={state.browserConnected?'success':''}>{state.browserConnected?'✓':'○'} 浏览器已连接</span><span className={capability.profileAuthenticated?'success':''}>{capability.profileAuthenticated?'✓':'○'} 抖音登录状态正常</span></div><button disabled={capability.loginAction==='unavailable'||state.loginWindowState==='opening'} onClick={()=>void run(capability.loginAction==='confirm'?onLoginComplete:onLogin,true)}>{loginLabel}</button></div><div className="card action"><div className="icon sync">↻</div><h3>立即同步</h3><p>采集账号、作品与运营数据，加密后上传至 XMT。</p><button disabled={!capability.canSync} onClick={()=>void run(async()=>setResult(await onSync(true)))}>小范围同步</button><button disabled={!capability.canSync} onClick={()=>void run(async()=>setResult(await onSync(false)))}>{state.syncing?'同步中…':'开始同步'}</button></div><div className="card action"><div className="icon">⌁</div><h3>封面来源检查</h3><p>仅本地检查当前绑定账号的作品封面来源；不上传服务器、不修改生产数据、不下载 Excel。</p><button aria-label="检查最新封面来源，仅本地执行" disabled={!canInspect} onClick={()=>void inspect()}>{inspecting?'检查中…':'检查最新封面来源（仅本地）'}</button>{cover?<p className="connection-checks">作品 {cover.works_seen} · 有候选 {cover.works_with_candidates} · 无候选 {cover.works_without_candidates} · 有效图片 {cover.probe_summary.valid_images} · 403 {cover.probe_summary.forbidden}</p>:null}</div></section><section className="card summary"><h3>运行诊断</h3><div className="metrics"><div><strong>{identity.buildId}</strong><span>Build ID</span></div><div><strong>{identity.packaged?'true':'false'}</strong><span>Packaged</span></div><div><strong>{identity.databaseReady?'已初始化':'未就绪'}</strong><span>数据库 / upload_queue</span></div><div><strong>{identity.apiTarget}</strong><span>API classification</span></div></div></section><section className="card summary"><h3>最近同步</h3><div className="metrics"><div><strong>{state.lastSyncAt?new Date(state.lastSyncAt).toLocaleString():'尚未同步'}</strong><span>同步时间</span></div><div><strong>{result?.snapshot.videos.length??'—'}</strong><span>作品数</span></div><div><strong>{result?.upload.success?'上传成功':'—'}</strong><span>上传状态</span></div></div></section></div>;
}
