import express from 'express';
import { authenticate } from '../middleware/auth.js';
import { acceptCreatorAgentReport, getCreatorCenterData, registerCreatorAgent } from '../services/creatorAgent.js';
import { getUnifiedCreatorCenterData } from '../services/creatorDataCenter.js';
import { acceptCreatorDataSync } from '../services/creatorSyncV291.js';
import { creatorInsightService, getCreatorInsights } from '../services/creatorInsights.js';
import { canManageCreatorAccount, grantCreatorAccountAccess } from '../services/creatorAccess.js';
import { canManageCreatorData, resolveManageScope, resolveViewScope } from '../services/creatorDataVisibility.js';
import { requirePermission } from '../middleware/permissions.js';
import { creatorAnalyticsService, type ReportType } from '../services/creatorAnalytics.js';
import { getDouyinDashboard, getDouyinSyncLogs, getDouyinTrends, getDouyinWorkDetail, getDouyinWorkReview, getDouyinWorks } from '../services/douyinDataCenter.js';
const router=express.Router();
const requestedPlatformUid = (value: unknown) => typeof value === 'string' && value.trim() ? value.trim() : undefined;
const resolveCreatorViewScope = (role: string, platformUid?: string) => resolveViewScope(role,'douyin',platformUid);
const resolveCreatorManageScope = (role: string, platformUid?: string) => resolveManageScope(role,'douyin',platformUid);
router.get('/douyin/dashboard',authenticate,requirePermission('creator:data:view'),async(req,res)=>{try{const scope=await resolveCreatorViewScope(req.user!.role,requestedPlatformUid(req.query.account_id));if(!scope)return res.status(404).json({message:'未找到已同步抖音账号'});const data=await getDouyinDashboard(scope.id);if(!data)return res.status(404).json({message:'该账号尚未完成标准化同步'});res.json({...data,access_level:scope.access_level});}catch(error){res.status(500).json({message:error instanceof Error?error.message:'抖音驾驶舱加载失败'});}});
router.get('/douyin/works',authenticate,requirePermission('creator:data:view'),async(req,res)=>{try{const scope=await resolveCreatorViewScope(req.user!.role,requestedPlatformUid(req.query.account_id));if(!scope)return res.status(404).json({message:'未找到已同步抖音账号'});res.json(await getDouyinWorks(scope.id,String(req.query.sort||'latest'),Number(req.query.limit)||20,requestedPlatformUid(req.query.cursor)));}catch(error){res.status(Number((error as {statusCode?:number}).statusCode||500)).json({message:error instanceof Error?error.message:'抖音作品库加载失败'});}});
router.get('/douyin/works/:id/review',authenticate,requirePermission('creator:data:view'),async(req,res)=>{try{const scope=await resolveCreatorViewScope(req.user!.role,requestedPlatformUid(req.query.account_id));if(!scope)return res.status(404).json({message:'未找到已同步抖音账号'});const data=await getDouyinWorkReview(scope.id,Number(req.params.id));if(!data)return res.status(404).json({message:'作品不存在或不在查看范围内'});res.json(data);}catch(error){res.status(500).json({message:error instanceof Error?error.message:'作品复盘加载失败'});}});
router.get('/douyin/works/:id',authenticate,requirePermission('creator:data:view'),async(req,res)=>{try{const scope=await resolveCreatorViewScope(req.user!.role,requestedPlatformUid(req.query.account_id));if(!scope)return res.status(404).json({message:'未找到已同步抖音账号'});const data=await getDouyinWorkDetail(scope.id,Number(req.params.id));if(!data)return res.status(404).json({message:'作品不存在或不在查看范围内'});res.json(data);}catch(error){res.status(500).json({message:error instanceof Error?error.message:'作品复盘加载失败'});}});
router.get('/douyin/trends',authenticate,requirePermission('creator:data:view'),async(req,res)=>{try{const scope=await resolveCreatorViewScope(req.user!.role,requestedPlatformUid(req.query.account_id));if(!scope)return res.status(404).json({message:'未找到已同步抖音账号'});const period=req.query.period==='7d'||req.query.period==='90d'?req.query.period:'30d';res.json(await getDouyinTrends(scope.id,period));}catch(error){res.status(500).json({message:error instanceof Error?error.message:'抖音趋势加载失败'});}});
router.get('/douyin/sync-logs',authenticate,requirePermission('creator:data:view'),async(req,res)=>{try{const scope=await resolveCreatorViewScope(req.user!.role,requestedPlatformUid(req.query.account_id));if(!scope)return res.status(404).json({message:'未找到已同步抖音账号'});res.json(await getDouyinSyncLogs(scope.id));}catch(error){res.status(500).json({message:error instanceof Error?error.message:'同步日志加载失败'});}});
router.post('/register',authenticate,requirePermission('creator:data:manage'),async(req,res)=>{
  try{if(!canManageCreatorData(req.user!.role))return res.status(403).json({success:false,message:'仅管理员或负责人可绑定 Creator Agent'});res.status(201).json(await registerCreatorAgent(req.user!.id,String(req.body?.platform||''),String(req.body?.account_id||''),String(req.body?.device_id||'')));}
  catch(error){res.status(Number((error as {statusCode?:number}).statusCode||500)).json({success:false,message:error instanceof Error?error.message:'注册失败'});}
});
router.post('/report',async(req,res)=>{
  try{
    if(process.env.NODE_ENV==='production'&&!req.secure)return res.status(426).json({success:false,message:'Creator Agent 仅允许通过 HTTPS 上传'});
    res.status(201).json(await acceptCreatorAgentReport(req.body||{},req.header('authorization')));
  }catch(error){res.status(Number((error as {statusCode?:number}).statusCode||500)).json({success:false,message:error instanceof Error?error.message:'上传失败'});}
});
router.post('/data-sync',async(req,res)=>{
  try{
    if(process.env.NODE_ENV==='production'&&!req.secure)return res.status(426).json({success:false,message:'Creator Agent 仅允许通过 HTTPS 上传'});
    res.status(201).json(await acceptCreatorDataSync(req.body||{},req.header('authorization')));
  }catch(error){res.status(Number((error as {statusCode?:number}).statusCode||500)).json({success:false,message:error instanceof Error?error.message:'统一数据同步失败'});}
});
router.get('/data',authenticate,requirePermission('creator:data:view'),async(req,res)=>{try{const scope=await resolveCreatorViewScope(req.user!.role,requestedPlatformUid(req.query.account_id));if(!scope)return res.json({account:null,works:[],dashboard:null,fans:null,history:[],trends:[],insights:{},analytics:{},data_sources:['local_creator_center']});const [data,insights,analytics]=await Promise.all([(async()=>(await getUnifiedCreatorCenterData(scope.user_id,scope.platform_uid))??(await getCreatorCenterData(scope.user_id,scope.platform_uid)))(),getCreatorInsights(scope.id),creatorAnalyticsService.overview(scope.id)]);res.json({...data,access_level:scope.access_level,insights,analytics});}catch(error){res.status(500).json({success:false,message:error instanceof Error?error.message:'查询失败'});}});
router.post('/insights/refresh',authenticate,requirePermission('creator:data:manage'),async(req,res)=>{try{const scope=await resolveCreatorManageScope(req.user!.role,requestedPlatformUid(req.body?.account_id));if(!scope)return res.status(403).json({message:'仅管理员或负责人可管理账号'});res.json(await creatorInsightService.generate(scope.id));}catch(error){res.status(500).json({message:error instanceof Error?error.message:'分析失败'});}});
router.post('/accounts/:id/access',authenticate,requirePermission('creator:data:manage'),async(req,res)=>{try{const accountId=Number(req.params.id),userId=Number(req.body?.user_id),accessLevel=req.body?.access_level==='manage'?'manage':'view';if(!await canManageCreatorAccount(req.user!.id,req.user!.role,accountId))return res.status(403).json({message:'不在账号管理范围内'});res.json(await grantCreatorAccountAccess(accountId,userId,accessLevel));}catch(error){res.status(400).json({message:error instanceof Error?error.message:'授权失败'});}});

router.get('/works/:id/analysis',authenticate,requirePermission('creator:data:view'),async(req,res)=>{try{const scope=await resolveCreatorViewScope(req.user!.role,requestedPlatformUid(req.query.account_id));if(!scope)return res.status(404).json({message:'未找到已同步账号'});const period=req.query.period==='24h'||req.query.period==='30d'?req.query.period:'7d';const analysis=await creatorAnalyticsService.work(scope.id,Number(req.params.id),period);if(!analysis)return res.status(404).json({message:'作品不存在或不在查看范围内'});res.json(analysis);}catch(error){res.status(500).json({message:error instanceof Error?error.message:'作品分析失败'});}});
router.get('/trends',authenticate,requirePermission('creator:data:view'),async(req,res)=>{try{const scope=await resolveCreatorViewScope(req.user!.role,requestedPlatformUid(req.query.account_id));if(!scope)return res.status(404).json({message:'未找到已同步账号'});const period=req.query.period==='7d'||req.query.period==='90d'?req.query.period:'30d';res.json(await creatorAnalyticsService.trends(scope.id,period));}catch(error){res.status(500).json({message:error instanceof Error?error.message:'趋势计算失败'});}});
router.get('/fans-analysis',authenticate,requirePermission('creator:data:view'),async(req,res)=>{try{const scope=await resolveCreatorViewScope(req.user!.role,requestedPlatformUid(req.query.account_id));if(!scope)return res.status(404).json({message:'未找到已同步账号'});res.json(await creatorAnalyticsService.fans(scope.id,Number(req.query.compare_days)||30));}catch(error){res.status(500).json({message:error instanceof Error?error.message:'粉丝分析失败'});}});
router.get('/reports',authenticate,requirePermission('creator:report:view'),async(req,res)=>{try{const scope=await resolveCreatorViewScope(req.user!.role,requestedPlatformUid(req.query.account_id));if(!scope)return res.status(404).json({message:'未找到已同步账号'});res.json(await creatorAnalyticsService.reports(scope.id));}catch(error){res.status(500).json({message:error instanceof Error?error.message:'报告查询失败'});}});
router.post('/reports/generate',authenticate,requirePermission('creator:report:manage'),async(req,res)=>{try{const scope=await resolveCreatorManageScope(req.user!.role,requestedPlatformUid(req.body?.account_id));if(!scope)return res.status(403).json({message:'仅管理员或负责人可管理账号'});const type:ReportType=req.body?.type==='daily'||req.body?.type==='monthly'?req.body.type:'weekly';res.status(201).json(await creatorAnalyticsService.generateReport(scope.id,type));}catch(error){res.status(500).json({message:error instanceof Error?error.message:'报告生成失败'});}});
export default router;
