import express from 'express';
import { authenticate } from '../middleware/auth.js';
import { requirePermission } from '../middleware/permissions.js';
import { createAuthorizationUrl, completeAuthorization } from '../services/douyin/auth.service.js';
import { receiveWebhook, verifyWebhook } from '../services/douyin/webhook.service.js';
import { queryAll, queryOne, execute } from '../database/utils.js';
const router = express.Router();

for (const path of ['/oauth/url', '/auth/url']) router.get(path, authenticate, requirePermission('douyin:account'), (req, res) => { try { res.json({ authorization_url: createAuthorizationUrl(req.user!.id) }); } catch (error) { res.status(503).json({ message: (error as Error).message }); } });
router.get('/oauth/callback', async (req, res) => { const { code,state,error } = req.query; if (error || !code || !state) return res.status(400).send('抖音授权未完成。'); try { const result = await completeAuthorization(String(code),String(state)); res.send(`抖音账号绑定成功（账号 #${result.accountId}）。请关闭此窗口返回 XMT。`); } catch (cause) { res.status(400).send(`抖音账号绑定失败：${(cause as Error).message}`); } });
router.get('/accounts', authenticate, requirePermission('douyin:view'), async (req,res) => { const ownOnly=req.user!.role!=='admin'&&req.user!.role!=='director'; res.json(await queryAll(`SELECT id,user_id,open_id,union_id,nickname,avatar,expires_at,status,douyin_data_source,auth_type,created_at,updated_at,(SELECT MAX(created_at) FROM douyin_sync_logs l WHERE l.account_id=douyin_accounts.id) last_sync_at FROM douyin_accounts WHERE open_id IS NOT NULL ${ownOnly?'AND user_id=?':''} ORDER BY updated_at DESC,created_at DESC`,ownOnly?[req.user!.id]:[])); });
router.post('/accounts/bind', authenticate, requirePermission('douyin:account'), (req,res) => { try { res.json({ authorization_url:createAuthorizationUrl(req.user!.id) }); } catch(error) { res.status(503).json({message:(error as Error).message}); } });
router.delete('/accounts/:id', authenticate, requirePermission('douyin:account'), async (req,res) => { const row=await queryOne<{user_id:number}>('SELECT user_id FROM douyin_accounts WHERE id=?',[req.params.id]); if(!row)return res.status(404).json({message:'账号不存在'}); if(req.user!.role!=='admin'&&req.user!.role!=='director'&&row.user_id!==req.user!.id)return res.status(403).json({message:'无权解绑该账号'}); await execute(`UPDATE douyin_accounts SET status='revoked',access_token_encrypt=NULL,refresh_token_encrypt=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?`,[req.params.id]); res.status(204).end(); });
for(const path of ['/videos','/statistics','/dashboard'])router.get(path,authenticate,(_req,res)=>res.status(410).json({message:'运营数据已统一由 Creator Agent 采集'}));
for(const path of ['/sync','/sync/account','/sync/videos','/sync/statistics'])router.post(path,authenticate,requirePermission('douyin:sync'),(_req,res)=>res.status(410).json({message:'官方 API 运营数据同步已停用，请使用 Creator Agent'}));
router.post('/webhook', async(req,res)=>{const raw=(req as express.Request&{rawBody?:Buffer}).rawBody?.toString('utf8')||JSON.stringify(req.body??{});let event:Record<string,unknown>;try{event=JSON.parse(raw);}catch{return res.status(400).json({message:'Webhook 请求体不是合法 JSON'});}if(event.event==='verify_webhook')return res.status(200).json({challenge:(event.content as {challenge?:unknown}|undefined)?.challenge});if(!verifyWebhook(raw,req.header('X-Douyin-Signature')||undefined))return res.status(401).json({message:'Webhook 验签失败'});const result=await receiveWebhook(event);res.status(result.duplicate?200:202).json({accepted:!result.duplicate,duplicate:result.duplicate});});
export default router;
