import express from 'express';
import { authenticate } from '../middleware/auth.js';
import { requirePermission } from '../middleware/permissions.js';
import { execute,executeInsert,queryAll,queryOne } from '../database/utils.js';
const router=express.Router();router.use(authenticate);
const manager=(role?:string)=>role==='admin'||role==='director';
const encodeIds=(value:unknown)=>JSON.stringify(Array.isArray(value)?value:[]);
const shape=(row:Record<string,unknown>)=>({...row,receiver_ids:JSON.parse(String(row.receiver_ids||'[]')),cc_user_ids:JSON.parse(String(row.cc_user_ids||'[]'))});
router.get('/',requirePermission('report:view'),async(req,res,next)=>{try{const elevated=manager(req.user!.role);const rows=await queryAll<Record<string,unknown>>(`SELECT r.*,u.name user_name FROM daily_reports r LEFT JOIN users u ON u.id=r.user_id WHERE ${elevated?'1=1':'r.user_id=?'} ORDER BY r.report_date DESC,r.updated_at DESC`,elevated?[]:[req.user!.id]);res.json({success:true,data:rows.map(shape)});}catch(error){next(error);}});
router.post('/',requirePermission('report:create'),async(req,res,next)=>{try{const b=req.body||{};if(!/^\d{4}-\d{2}-\d{2}$/.test(String(b.report_date||'')))return res.status(400).json({success:false,message:'report_date 必须为 YYYY-MM-DD'});const id=await executeInsert(`INSERT INTO daily_reports(user_id,report_date,content,summary,tomorrow_plan,status,receiver_ids,cc_user_ids,manual_summary_md,created_at,updated_at)VALUES(?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`,[req.user!.id,b.report_date,String(b.content||''),String(b.summary||''),String(b.tomorrow_plan||''),String(b.status||'draft'),encodeIds(b.receiver_ids),encodeIds(b.cc_user_ids),String(b.summary||'')]);res.status(201).json({success:true,data:shape((await queryOne<Record<string,unknown>>('SELECT * FROM daily_reports WHERE id=?',[id]))!)});}catch(error){next(error);}});
router.get('/:id',requirePermission('report:view'),async(req,res,next)=>{try{const row=await queryOne<Record<string,unknown>>('SELECT * FROM daily_reports WHERE id=?',[req.params.id]);if(!row)return res.status(404).json({success:false,message:'日报不存在'});if(!manager(req.user!.role)&&Number(row.user_id)!==req.user!.id)return res.status(403).json({success:false,message:'无权查看该日报'});res.json({success:true,data:shape(row)});}catch(error){next(error);}});
router.put('/:id',requirePermission('report:create'),async(req,res,next)=>{try{const row=await queryOne<Record<string,unknown>>('SELECT * FROM daily_reports WHERE id=?',[req.params.id]);if(!row)return res.status(404).json({success:false,message:'日报不存在'});if(Number(row.user_id)!==req.user!.id&&!manager(req.user!.role))return res.status(403).json({success:false,message:'只能编辑自己的日报'});const b=req.body||{};await execute(`UPDATE daily_reports SET content=?,summary=?,tomorrow_plan=?,status=?,receiver_ids=?,cc_user_ids=?,manual_summary_md=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`,[String(b.content??row.content??''),String(b.summary??row.summary??''),String(b.tomorrow_plan??row.tomorrow_plan??''),String(b.status??row.status??'draft'),encodeIds(b.receiver_ids??JSON.parse(String(row.receiver_ids||'[]'))),encodeIds(b.cc_user_ids??JSON.parse(String(row.cc_user_ids||'[]'))),String(b.summary??row.summary??''),req.params.id]);res.json({success:true,data:shape((await queryOne<Record<string,unknown>>('SELECT * FROM daily_reports WHERE id=?',[req.params.id]))!)});}catch(error){next(error);}});
// report:create is deliberate: employees may delete their own report; ownership is checked below.
router.delete('/:id',requirePermission('report:create'),async(req,res,next)=>{try{const row=await queryOne<Record<string,unknown>>('SELECT * FROM daily_reports WHERE id=?',[req.params.id]);if(!row)return res.status(404).json({success:false,message:'日报不存在'});if(Number(row.user_id)!==req.user!.id&&!manager(req.user!.role))return res.status(403).json({success:false,message:'只能删除自己的日报'});await execute('DELETE FROM daily_reports WHERE id=?',[req.params.id]);res.status(204).end();}catch(error){next(error);}});
export default router;
